# Generated by Django 4.0.3 on 2022-05-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease', models.IntegerField()),
                ('utilities', models.IntegerField()),
                ('equipment', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('materials', models.IntegerField()),
                ('preparations', models.IntegerField()),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
    ]
