# Generated by Django 4.0.3 on 2022-05-24 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50)),
                ('time', models.DateTimeField(blank=True)),
                ('ownership', models.TextField(null=True)),
                ('preparations', models.TextField(null=True)),
                ('total', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True, max_length=50)),
                ('quantity', models.IntegerField(blank=True)),
                ('date_of_receipt', models.DateTimeField(null=True)),
                ('date_of_issue', models.DateTimeField(null=True)),
                ('date_of_process', models.DateTimeField(null=True)),
                ('total', models.IntegerField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receiver.client')),
                ('services', models.ManyToManyField(to='receiver.service')),
            ],
        ),
    ]
