# Generated by Django 4.0.3 on 2022-05-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50)),
                ('time', models.DateTimeField(blank=True)),
                ('ownership', models.TextField(null=True)),
                ('preparations', models.TextField(null=True)),
                ('total', models.IntegerField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True, max_length=50)),
                ('quantity', models.IntegerField(blank=True)),
                ('date_of_receipt', models.DateTimeField(null=True)),
                ('date_of_issue', models.DateTimeField(null=True)),
                ('date_of_process', models.DateTimeField(null=True)),
                ('total', models.IntegerField(blank=True, max_length=50)),
                ('services', models.ManyToManyField(to='receiver.service')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True, max_length=50)),
                ('middle_name', models.TextField(blank=True, max_length=50)),
                ('last_name', models.TextField(blank=True, max_length=50)),
                ('phone', models.TextField(blank=True, max_length=50)),
                ('orders', models.ManyToManyField(to='receiver.order')),
            ],
        ),
    ]
