# Generated by Django 4.0.3 on 2022-05-28 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0003_alter_service_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='services',
        ),
        migrations.AddField(
            model_name='order',
            name='clothes',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='receiver.service'),
            preserve_default=False,
        ),
    ]
